# Generated by Django 2.2.1 on 2019-08-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
