# Generated by Django 2.2.1 on 2019-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_app', '0006_garbage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gar_location', models.CharField(max_length=50)),
                ('gar_checkpoint', models.CharField(max_length=50)),
            ],
        ),
    ]
