# Generated by Django 2.2.1 on 2019-09-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_app', '0007_checkpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkpoint_dustbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(max_length=10)),
                ('yellow_bin', models.CharField(max_length=50)),
                ('green_bin', models.CharField(max_length=50)),
                ('red_bin', models.CharField(max_length=50)),
                ('blue_bin', models.CharField(max_length=50)),
                ('distance1', models.CharField(max_length=10)),
                ('distance2', models.CharField(max_length=10)),
                ('distance3', models.CharField(max_length=10)),
                ('distance4', models.CharField(max_length=10)),
                ('distance5', models.CharField(max_length=10)),
                ('distance6', models.CharField(max_length=10)),
                ('distance7', models.CharField(max_length=10)),
                ('distance8', models.CharField(max_length=10)),
                ('distance9', models.CharField(max_length=10)),
                ('distance10', models.CharField(max_length=10)),
                ('distance11', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='driver_checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint1', models.CharField(max_length=50)),
                ('checkpoint2', models.CharField(max_length=50)),
                ('checkpoint3', models.CharField(max_length=50)),
                ('checkpoint4', models.CharField(max_length=50)),
            ],
        ),
    ]
